name: build-image

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      repository: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: ([[ $GITHUB_REF == refs/tags/* ]] && echo tag=${GITHUB_REF##*/} || echo tag=latest) >> $GITHUB_ENV
      - run: docker build . --tag $repository:$tag --cache-from $repository:latest
      - run: docker push $repository:$tag
        if: github.event_name == 'push'
